#!/bin/bash

# PropAI Secure Environment Setup Script
# 이 스크립트는 민감한 환경 변수를 화면에 노출(에코)시키지 않고 안전하게 파일로 저장합니다.

CONTRACTS_ENV_PATH="contracts/.env"

echo "🔐 PropAI 스마트 컨트랙트 배포 계정 안전 설정 마법사"
echo "--------------------------------------------------------"
echo "입력하시는 모든 비밀 키는 화면에 표시되지 않으므로 안심하세요."
echo "--------------------------------------------------------"

# 1. RPC URL
read -p "1. POLYGON_AMOY_RPC_URL 을 입력하세요 (입력 후 Enter): " RPC_URL

# 2. Private Key (-s: 입력 내용이 화면에 표시되지 않음)
read -s -p "2. DEPLOYER_PRIVATE_KEY (마스터 개인키) 를 입력하세요 (입력 후 Enter): " PRIVATE_KEY
echo ""

# 3. Polygonscan API Key
read -s -p "3. POLYGONSCAN_API_KEY 을 입력하세요 (입력 후 Enter): " SCAN_API_KEY
echo ""
echo "--------------------------------------------------------"

# .env 파일 생성 및 권한 강화
# 기존 파일이 있다면 덮어쓰거나 추가해야 하지만, 여기서는 덮어쓰기 방식으로 안내
cat << EOF > $CONTRACTS_ENV_PATH
# PropAI Contracts Environment Variables
# Auto-generated by setup-env.sh

POLYGON_AMOY_RPC_URL="$RPC_URL"
DEPLOYER_PRIVATE_KEY="$PRIVATE_KEY"
POLYGONSCAN_API_KEY="$SCAN_API_KEY"
EOF

# 본인만 읽고 쓸 수 있도록 파일 권한 변경 (600)
chmod 600 $CONTRACTS_ENV_PATH

echo "✅ 성공: $CONTRACTS_ENV_PATH 파일이 안전하게 생성되었습니다!"
echo "이제 코드에 키를 하드코딩하지 않고 안전하게 배포 파이프라인을 실행할 수 있습니다."
