/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ReentrantRefundAttackerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attackOnReceive"
      | "createEscrowAndFund"
      | "escrow"
      | "escrowId"
      | "reentrancyBlocked"
      | "setAttackOnReceive"
      | "triggerRefund"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "attackOnReceive",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createEscrowAndFund",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "escrow", values?: undefined): string;
  encodeFunctionData(functionFragment: "escrowId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reentrancyBlocked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAttackOnReceive",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "triggerRefund",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "attackOnReceive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEscrowAndFund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "escrowId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reentrancyBlocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAttackOnReceive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerRefund",
    data: BytesLike
  ): Result;
}

export interface ReentrantRefundAttacker extends BaseContract {
  connect(runner?: ContractRunner | null): ReentrantRefundAttacker;
  waitForDeployment(): Promise<this>;

  interface: ReentrantRefundAttackerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attackOnReceive: TypedContractMethod<[], [boolean], "view">;

  createEscrowAndFund: TypedContractMethod<
    [payee: AddressLike, expiresAt: BigNumberish, conditionHash: BytesLike],
    [void],
    "payable"
  >;

  escrow: TypedContractMethod<[], [string], "view">;

  escrowId: TypedContractMethod<[], [bigint], "view">;

  reentrancyBlocked: TypedContractMethod<[], [boolean], "view">;

  setAttackOnReceive: TypedContractMethod<
    [nextValue: boolean],
    [void],
    "nonpayable"
  >;

  triggerRefund: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attackOnReceive"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "createEscrowAndFund"
  ): TypedContractMethod<
    [payee: AddressLike, expiresAt: BigNumberish, conditionHash: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "escrow"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "escrowId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reentrancyBlocked"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "setAttackOnReceive"
  ): TypedContractMethod<[nextValue: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "triggerRefund"
  ): TypedContractMethod<[], [void], "nonpayable">;

  filters: {};
}
