/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace DrawRegistry {
  export type DrawStruct = {
    commitHash: BytesLike;
    participantsHash: BytesLike;
    nonce: BytesLike;
    resultRoot: BytesLike;
    committedAt: BigNumberish;
    revealedAt: BigNumberish;
  };

  export type DrawStructOutput = [
    commitHash: string,
    participantsHash: string,
    nonce: string,
    resultRoot: string,
    committedAt: bigint,
    revealedAt: bigint
  ] & {
    commitHash: string;
    participantsHash: string;
    nonce: string;
    resultRoot: string;
    committedAt: bigint;
    revealedAt: bigint;
  };
}

export interface DrawRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "commitDraw"
      | "commitPrecededReveal"
      | "getDraw"
      | "operators"
      | "owner"
      | "renounceOwnership"
      | "revealDraw"
      | "setOperator"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DrawCommitted"
      | "DrawRevealed"
      | "OperatorSet"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "commitDraw",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "commitPrecededReveal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getDraw", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "operators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revealDraw",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOperator",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "commitDraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "commitPrecededReveal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDraw", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "operators", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revealDraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DrawCommittedEvent {
  export type InputTuple = [
    drawId: BytesLike,
    commitHash: BytesLike,
    participantsHash: BytesLike,
    at: BigNumberish
  ];
  export type OutputTuple = [
    drawId: string,
    commitHash: string,
    participantsHash: string,
    at: bigint
  ];
  export interface OutputObject {
    drawId: string;
    commitHash: string;
    participantsHash: string;
    at: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DrawRevealedEvent {
  export type InputTuple = [
    drawId: BytesLike,
    nonce: BytesLike,
    resultRoot: BytesLike,
    at: BigNumberish
  ];
  export type OutputTuple = [
    drawId: string,
    nonce: string,
    resultRoot: string,
    at: bigint
  ];
  export interface OutputObject {
    drawId: string;
    nonce: string;
    resultRoot: string;
    at: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorSetEvent {
  export type InputTuple = [who: AddressLike, allowed: boolean];
  export type OutputTuple = [who: string, allowed: boolean];
  export interface OutputObject {
    who: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DrawRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): DrawRegistry;
  waitForDeployment(): Promise<this>;

  interface: DrawRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  commitDraw: TypedContractMethod<
    [drawId: BytesLike, commitHash: BytesLike, participantsHash: BytesLike],
    [void],
    "nonpayable"
  >;

  commitPrecededReveal: TypedContractMethod<
    [drawId: BytesLike],
    [boolean],
    "view"
  >;

  getDraw: TypedContractMethod<
    [drawId: BytesLike],
    [DrawRegistry.DrawStructOutput],
    "view"
  >;

  operators: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revealDraw: TypedContractMethod<
    [drawId: BytesLike, nonce: BytesLike, resultRoot: BytesLike],
    [void],
    "nonpayable"
  >;

  setOperator: TypedContractMethod<
    [who: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "commitDraw"
  ): TypedContractMethod<
    [drawId: BytesLike, commitHash: BytesLike, participantsHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "commitPrecededReveal"
  ): TypedContractMethod<[drawId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getDraw"
  ): TypedContractMethod<
    [drawId: BytesLike],
    [DrawRegistry.DrawStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "operators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revealDraw"
  ): TypedContractMethod<
    [drawId: BytesLike, nonce: BytesLike, resultRoot: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setOperator"
  ): TypedContractMethod<
    [who: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DrawCommitted"
  ): TypedContractEvent<
    DrawCommittedEvent.InputTuple,
    DrawCommittedEvent.OutputTuple,
    DrawCommittedEvent.OutputObject
  >;
  getEvent(
    key: "DrawRevealed"
  ): TypedContractEvent<
    DrawRevealedEvent.InputTuple,
    DrawRevealedEvent.OutputTuple,
    DrawRevealedEvent.OutputObject
  >;
  getEvent(
    key: "OperatorSet"
  ): TypedContractEvent<
    OperatorSetEvent.InputTuple,
    OperatorSetEvent.OutputTuple,
    OperatorSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "DrawCommitted(bytes32,bytes32,bytes32,uint64)": TypedContractEvent<
      DrawCommittedEvent.InputTuple,
      DrawCommittedEvent.OutputTuple,
      DrawCommittedEvent.OutputObject
    >;
    DrawCommitted: TypedContractEvent<
      DrawCommittedEvent.InputTuple,
      DrawCommittedEvent.OutputTuple,
      DrawCommittedEvent.OutputObject
    >;

    "DrawRevealed(bytes32,bytes32,bytes32,uint64)": TypedContractEvent<
      DrawRevealedEvent.InputTuple,
      DrawRevealedEvent.OutputTuple,
      DrawRevealedEvent.OutputObject
    >;
    DrawRevealed: TypedContractEvent<
      DrawRevealedEvent.InputTuple,
      DrawRevealedEvent.OutputTuple,
      DrawRevealedEvent.OutputObject
    >;

    "OperatorSet(address,bool)": TypedContractEvent<
      OperatorSetEvent.InputTuple,
      OperatorSetEvent.OutputTuple,
      OperatorSetEvent.OutputObject
    >;
    OperatorSet: TypedContractEvent<
      OperatorSetEvent.InputTuple,
      OperatorSetEvent.OutputTuple,
      OperatorSetEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
