/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SubcontractPaymentInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOMINATOR"
      | "MAX_RETENTION_RATE"
      | "approveSubcontract"
      | "claimPayment"
      | "claims"
      | "completeSubcontract"
      | "disputeSubcontract"
      | "nextClaimId"
      | "nextSubcontractId"
      | "owner"
      | "pause"
      | "paused"
      | "registerSubcontract"
      | "rejectClaim"
      | "releaseDirectPayment"
      | "releaseRetention"
      | "renounceOwnership"
      | "retentionBalance"
      | "subcontracts"
      | "transferOwnership"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DirectPaymentReleased"
      | "OwnershipTransferred"
      | "Paused"
      | "PaymentClaimed"
      | "RetentionReleased"
      | "SubcontractApproved"
      | "SubcontractCompleted"
      | "SubcontractDisputed"
      | "SubcontractRegistered"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_RETENTION_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveSubcontract",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimPayment",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "claims",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "completeSubcontract",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeSubcontract",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextClaimId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextSubcontractId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerSubcontract",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectClaim",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseDirectPayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseRetention",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "retentionBalance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subcontracts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "BPS_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_RETENTION_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveSubcontract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claims", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completeSubcontract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeSubcontract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextClaimId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextSubcontractId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerSubcontract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseDirectPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseRetention",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retentionBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subcontracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace DirectPaymentReleasedEvent {
  export type InputTuple = [
    claimId: BigNumberish,
    subcontractId: BigNumberish,
    subcontractor: AddressLike,
    netAmount: BigNumberish,
    retention: BigNumberish
  ];
  export type OutputTuple = [
    claimId: bigint,
    subcontractId: bigint,
    subcontractor: string,
    netAmount: bigint,
    retention: bigint
  ];
  export interface OutputObject {
    claimId: bigint;
    subcontractId: bigint;
    subcontractor: string;
    netAmount: bigint;
    retention: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentClaimedEvent {
  export type InputTuple = [
    claimId: BigNumberish,
    subcontractId: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    claimId: bigint,
    subcontractId: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    claimId: bigint;
    subcontractId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RetentionReleasedEvent {
  export type InputTuple = [
    subcontractId: BigNumberish,
    subcontractor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    subcontractId: bigint,
    subcontractor: string,
    amount: bigint
  ];
  export interface OutputObject {
    subcontractId: bigint;
    subcontractor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubcontractApprovedEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubcontractCompletedEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubcontractDisputedEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubcontractRegisteredEvent {
  export type InputTuple = [
    id: BigNumberish,
    generalContractor: AddressLike,
    subcontractor: AddressLike,
    totalAmount: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    generalContractor: string,
    subcontractor: string,
    totalAmount: bigint
  ];
  export interface OutputObject {
    id: bigint;
    generalContractor: string;
    subcontractor: string;
    totalAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SubcontractPayment extends BaseContract {
  connect(runner?: ContractRunner | null): SubcontractPayment;
  waitForDeployment(): Promise<this>;

  interface: SubcontractPaymentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  MAX_RETENTION_RATE: TypedContractMethod<[], [bigint], "view">;

  approveSubcontract: TypedContractMethod<
    [_id: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimPayment: TypedContractMethod<
    [
      _subcontractId: BigNumberish,
      _amount: BigNumberish,
      _workDescription: string
    ],
    [bigint],
    "nonpayable"
  >;

  claims: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, bigint, bigint] & {
        subcontractId: bigint;
        amount: bigint;
        workDescription: string;
        claimDate: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  completeSubcontract: TypedContractMethod<
    [_id: BigNumberish],
    [void],
    "nonpayable"
  >;

  disputeSubcontract: TypedContractMethod<
    [_id: BigNumberish],
    [void],
    "nonpayable"
  >;

  nextClaimId: TypedContractMethod<[], [bigint], "view">;

  nextSubcontractId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  registerSubcontract: TypedContractMethod<
    [
      _subcontractor: AddressLike,
      _totalAmount: BigNumberish,
      _retentionRate: BigNumberish,
      _startDate: BigNumberish,
      _endDate: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  rejectClaim: TypedContractMethod<
    [_claimId: BigNumberish],
    [void],
    "nonpayable"
  >;

  releaseDirectPayment: TypedContractMethod<
    [_claimId: BigNumberish],
    [void],
    "payable"
  >;

  releaseRetention: TypedContractMethod<
    [_subcontractId: BigNumberish],
    [void],
    "payable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  retentionBalance: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  subcontracts: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint, bigint] & {
        generalContractor: string;
        subcontractor: string;
        totalAmount: bigint;
        paidAmount: bigint;
        retentionRate: bigint;
        startDate: bigint;
        endDate: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_RETENTION_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approveSubcontract"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimPayment"
  ): TypedContractMethod<
    [
      _subcontractId: BigNumberish,
      _amount: BigNumberish,
      _workDescription: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claims"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, bigint, bigint] & {
        subcontractId: bigint;
        amount: bigint;
        workDescription: string;
        claimDate: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "completeSubcontract"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "disputeSubcontract"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "nextClaimId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextSubcontractId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerSubcontract"
  ): TypedContractMethod<
    [
      _subcontractor: AddressLike,
      _totalAmount: BigNumberish,
      _retentionRate: BigNumberish,
      _startDate: BigNumberish,
      _endDate: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rejectClaim"
  ): TypedContractMethod<[_claimId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releaseDirectPayment"
  ): TypedContractMethod<[_claimId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "releaseRetention"
  ): TypedContractMethod<[_subcontractId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "retentionBalance"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "subcontracts"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint, bigint] & {
        generalContractor: string;
        subcontractor: string;
        totalAmount: bigint;
        paidAmount: bigint;
        retentionRate: bigint;
        startDate: bigint;
        endDate: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "DirectPaymentReleased"
  ): TypedContractEvent<
    DirectPaymentReleasedEvent.InputTuple,
    DirectPaymentReleasedEvent.OutputTuple,
    DirectPaymentReleasedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentClaimed"
  ): TypedContractEvent<
    PaymentClaimedEvent.InputTuple,
    PaymentClaimedEvent.OutputTuple,
    PaymentClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RetentionReleased"
  ): TypedContractEvent<
    RetentionReleasedEvent.InputTuple,
    RetentionReleasedEvent.OutputTuple,
    RetentionReleasedEvent.OutputObject
  >;
  getEvent(
    key: "SubcontractApproved"
  ): TypedContractEvent<
    SubcontractApprovedEvent.InputTuple,
    SubcontractApprovedEvent.OutputTuple,
    SubcontractApprovedEvent.OutputObject
  >;
  getEvent(
    key: "SubcontractCompleted"
  ): TypedContractEvent<
    SubcontractCompletedEvent.InputTuple,
    SubcontractCompletedEvent.OutputTuple,
    SubcontractCompletedEvent.OutputObject
  >;
  getEvent(
    key: "SubcontractDisputed"
  ): TypedContractEvent<
    SubcontractDisputedEvent.InputTuple,
    SubcontractDisputedEvent.OutputTuple,
    SubcontractDisputedEvent.OutputObject
  >;
  getEvent(
    key: "SubcontractRegistered"
  ): TypedContractEvent<
    SubcontractRegisteredEvent.InputTuple,
    SubcontractRegisteredEvent.OutputTuple,
    SubcontractRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "DirectPaymentReleased(uint256,uint256,address,uint256,uint256)": TypedContractEvent<
      DirectPaymentReleasedEvent.InputTuple,
      DirectPaymentReleasedEvent.OutputTuple,
      DirectPaymentReleasedEvent.OutputObject
    >;
    DirectPaymentReleased: TypedContractEvent<
      DirectPaymentReleasedEvent.InputTuple,
      DirectPaymentReleasedEvent.OutputTuple,
      DirectPaymentReleasedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PaymentClaimed(uint256,uint256,uint256)": TypedContractEvent<
      PaymentClaimedEvent.InputTuple,
      PaymentClaimedEvent.OutputTuple,
      PaymentClaimedEvent.OutputObject
    >;
    PaymentClaimed: TypedContractEvent<
      PaymentClaimedEvent.InputTuple,
      PaymentClaimedEvent.OutputTuple,
      PaymentClaimedEvent.OutputObject
    >;

    "RetentionReleased(uint256,address,uint256)": TypedContractEvent<
      RetentionReleasedEvent.InputTuple,
      RetentionReleasedEvent.OutputTuple,
      RetentionReleasedEvent.OutputObject
    >;
    RetentionReleased: TypedContractEvent<
      RetentionReleasedEvent.InputTuple,
      RetentionReleasedEvent.OutputTuple,
      RetentionReleasedEvent.OutputObject
    >;

    "SubcontractApproved(uint256)": TypedContractEvent<
      SubcontractApprovedEvent.InputTuple,
      SubcontractApprovedEvent.OutputTuple,
      SubcontractApprovedEvent.OutputObject
    >;
    SubcontractApproved: TypedContractEvent<
      SubcontractApprovedEvent.InputTuple,
      SubcontractApprovedEvent.OutputTuple,
      SubcontractApprovedEvent.OutputObject
    >;

    "SubcontractCompleted(uint256)": TypedContractEvent<
      SubcontractCompletedEvent.InputTuple,
      SubcontractCompletedEvent.OutputTuple,
      SubcontractCompletedEvent.OutputObject
    >;
    SubcontractCompleted: TypedContractEvent<
      SubcontractCompletedEvent.InputTuple,
      SubcontractCompletedEvent.OutputTuple,
      SubcontractCompletedEvent.OutputObject
    >;

    "SubcontractDisputed(uint256)": TypedContractEvent<
      SubcontractDisputedEvent.InputTuple,
      SubcontractDisputedEvent.OutputTuple,
      SubcontractDisputedEvent.OutputObject
    >;
    SubcontractDisputed: TypedContractEvent<
      SubcontractDisputedEvent.InputTuple,
      SubcontractDisputedEvent.OutputTuple,
      SubcontractDisputedEvent.OutputObject
    >;

    "SubcontractRegistered(uint256,address,address,uint256)": TypedContractEvent<
      SubcontractRegisteredEvent.InputTuple,
      SubcontractRegisteredEvent.OutputTuple,
      SubcontractRegisteredEvent.OutputObject
    >;
    SubcontractRegistered: TypedContractEvent<
      SubcontractRegisteredEvent.InputTuple,
      SubcontractRegisteredEvent.OutputTuple,
      SubcontractRegisteredEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
